package Vista;

import java.util.ArrayList;
import Controlador.*;
import Modelo.*;
import javax.swing.JOptionPane;

public class JFrame extends javax.swing.JFrame {

    Propietario propietario = new Propietario();
    
    public JFrame() {
        initComponents();
        
        usuario.setVisible(false);
        contraseña.setVisible(false);
        textUsu.setVisible(false);
        textCont.setVisible(false);
        BVisual.setEnabled(false);
        BAcerca.setEnabled(false);
        BAceptar.setVisible(false);
    }

    public void actualizarPanel(javax.swing.JPanel panel){
        this.setContentPane(panel);
        pack();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        textUsu = new javax.swing.JTextField();
        textCont = new javax.swing.JTextField();
        BAceptar = new javax.swing.JToggleButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        BAbrir = new javax.swing.JMenuItem();
        BCerrar = new javax.swing.JMenuItem();
        BVisual = new javax.swing.JMenu();
        BResumen = new javax.swing.JMenuItem();
        BDetalle = new javax.swing.JMenuItem();
        BAcerca = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 36)); // NOI18N
        titulo.setText("PRACTICA 5");

        usuario.setText("Usuario");

        contraseña.setText("Contraseña");

        textCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContActionPerformed(evt);
            }
        });

        BAceptar.setText("Aceptar");
        BAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(contraseña)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textCont))
                        .addComponent(titulo)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(usuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BAceptar)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña)
                    .addComponent(textCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BAceptar)
                .addGap(171, 171, 171))
        );

        jMenu5.setText("Conexion");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });

        BAbrir.setText("Abrir");
        BAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BAbrirMouseClicked(evt);
            }
        });
        BAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAbrirActionPerformed(evt);
            }
        });
        jMenu5.add(BAbrir);

        BCerrar.setText("Cerrar");
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });
        jMenu5.add(BCerrar);

        jMenuBar3.add(jMenu5);

        BVisual.setText("Visualizar");

        BResumen.setText("Resumen");
        BResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResumenActionPerformed(evt);
            }
        });
        BVisual.add(BResumen);

        BDetalle.setText("Detalle");
        BDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDetalleActionPerformed(evt);
            }
        });
        BVisual.add(BDetalle);

        jMenuBar3.add(BVisual);

        BAcerca.setText("Acerca De");
        BAcerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BAcercaMouseClicked(evt);
            }
        });
        BAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAcercaActionPerformed(evt);
            }
        });
        jMenuBar3.add(BAcerca);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAbrirMouseClicked

    }//GEN-LAST:event_BAbrirMouseClicked

    private void BAcercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAcercaMouseClicked
        Informacion info = new Informacion(this,true);
        info.setVisible(true);
        
    }//GEN-LAST:event_BAcercaMouseClicked

    private void BAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAbrirActionPerformed
        usuario.setVisible(true);
        contraseña.setVisible(true);
        textUsu.setVisible(true);
        textCont.setVisible(true);
        BAceptar.setVisible(true);
        textUsu.setText("MPEREZ");
        textCont.setText("2900");
        Conexion.open();
    }//GEN-LAST:event_BAbrirActionPerformed

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        Conexion.close();
        JOptionPane.showMessageDialog(rootPane,"Se ha cerrado sesion");
        BVisual.setEnabled(false);
        BAcerca.setEnabled(false);
        this.setVisible(true);
        titulo.setVisible(true);
        actualizarPanel(this.jPanel1);
    }//GEN-LAST:event_BCerrarActionPerformed

    private void BDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDetalleActionPerformed
                
        Visualizar visual = new Visualizar(propietario);
        actualizarPanel(visual);
    }//GEN-LAST:event_BDetalleActionPerformed

    private void BResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResumenActionPerformed
        ArrayList<Vehiculo> vehiculo = new ArrayList<Vehiculo>();
        vehiculo = VehiculoBD.getLista(propietario);
 
        Resumen resum = new Resumen(vehiculo,propietario);
        actualizarPanel(resum);
    }//GEN-LAST:event_BResumenActionPerformed

    private void textContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContActionPerformed

    private void BAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAceptarActionPerformed
        String Tusuario = textUsu.getText();
        String Tcontraseña = textCont.getText();
 
        propietario = PropietarioBD.getPropietario(Tusuario,Tcontraseña);

        if(propietario != null){
            usuario.setVisible(false);
            contraseña.setVisible(false);   
            textUsu.setVisible(false);
            textCont.setVisible(false);
            BAceptar.setVisible(false);
            BVisual.setEnabled(true);
            BAcerca.setEnabled(true);
        }
        
    }//GEN-LAST:event_BAceptarActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void BAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAcercaActionPerformed

    }//GEN-LAST:event_BAcercaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BAbrir;
    private javax.swing.JToggleButton BAceptar;
    private javax.swing.JMenu BAcerca;
    private javax.swing.JMenuItem BCerrar;
    private javax.swing.JMenuItem BDetalle;
    private javax.swing.JMenuItem BResumen;
    private javax.swing.JMenu BVisual;
    private javax.swing.JLabel contraseña;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textCont;
    private javax.swing.JTextField textUsu;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
